name: CI

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    working-directory: ecommerce

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: 'ecommerce/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Run Lint
        run: npx nx run-many -t lint


      - name: Run Build
        run: npx nx run-many -t build
